_wandb:
    value:
        cli_version: 0.23.0
        e:
            oxqqqzf45x90dsguks6wcpdg6edvn99c:
                codePath: c:\Users\salee\OneDrive\Documents\GitHub\ift-6758-m1\notebooks\advanced_models.ipynb
                codePathLocal: advanced_models.ipynb
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "997526073344"
                        used: "424748044288"
                email: saleem.ibrahim@umontreal.ca
                executable: c:\Users\salee\anaconda3\python.exe
                git:
                    commit: 8f2646c27f64cfb01391414e3641f0d0027787dd
                    remote: https://github.com/d1amondb0t/ift-6758-m1.git
                gpu: NVIDIA GeForce RTX 4070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4608
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4070 Laptop GPU
                      uuid: GPU-0f17deb3-28b8-56bf-7448-1c3523d2a9b9
                host: Sal33m
                memory:
                    total: "68374552576"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\salee\OneDrive\Documents\GitHub\ift-6758-m1\notebooks\advanced_models.ipynb
                python: CPython 3.11.3
                root: c:\Users\salee\OneDrive\Documents\GitHub\ift-6758-m1\notebooks
                startedAt: "2025-11-14T18:11:33.195286Z"
                writerId: oxqqqzf45x90dsguks6wcpdg6edvn99c
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 5
                - 6
                - 53
            "2":
                - 5
                - 6
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.11.3
            "5": 0.23.0
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.23.0
            "13": windows-amd64
models:
    value:
        - XGB_baseline
        - XGB_all_features
        - XGB_selected_features_corr
        - XGB_selected_features_var
        - XGB_selected_features_rfe
